# lightning.pytorch==2.1.1
seed_everything: 42
trainer:
  accelerator: gpu
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: 16-mixed
  logger: true
  callbacks:
    - class_path: RichProgressBar
    - class_path: LearningRateMonitor
      init_args:
        logging_interval: epoch
    - class_path: EarlyStopping
      init_args:
        monitor: val/loss
        mode: min
        patience: 20
    
  max_epochs: 100
  log_every_n_steps: 5
  default_root_dir: terramind_base_EnMAPCDL/
data:
  class_path: datamodules.enmap_cdl_nlcd.EnMAPCDLNLCDDataModule
  init_args:
    batch_size: 8
    num_workers: 8
    patch_size: 128
    sensor: "enmap"
    data_root: ./enmap_cdl/
    product: "cdl"
    classes: [0, 1, 2, 3, 4, 5, 6, 45, 54, 69, 72, 75, 76, 204, 210]


model:
  class_path: terratorch.tasks.SemanticSegmentationTask
  init_args:
    model_factory: EncoderDecoderFactory
    model_args:
      backbone: terramind_v1_base
      backbone_pretrained: true
      backbone_img_size: 128
      backbone_in_chans: 12
      backbone_modalities:
        - S2L2A
      backbone_bands:
        S2L2A: ["COASTAL_AEROSOL", "BLUE", "GREEN", "RED", "RED_EDGE_1", "RED_EDGE_2", "RED_EDGE_3", "NIR_BROAD", "NIR_NARROW", "WATER_VAPOR", "SWIR_1", "SWIR_2",]

      necks:
        - name: SelectIndices
          indices: [-1]
        - name: ReshapeTokensToImage
          remove_cls_token: True

      decoder: FCNDecoder
      decoder_channels: 256

      head_dropout: 0.21
      num_classes: 14
    loss: ce
    ignore_index: 14
    freeze_backbone: false
    freeze_decoder: false
    path_to_record_metrics: terramind_base_EnMAPCDL/checkpoints/
    class_names: ["Corn", "Cotton", "Rice", "Sorghum", "Soybeans", "Sunflower", "Sugarcane", "Tomatoes", "Grapes", "Citrus", "Almonds", "Walnuts", "Pistachios", "Prunes"]

optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 3.216e-5

lr_scheduler:
  class_path: CosineAnnealingLR
  init_args:
    optimizer: optimizer
    t_max: 10
    eta_min: 1e-5
