# lightning.pytorch==2.1.1
seed_everything: 42
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: 16-mixed
  logger:
    class_path: lightning.pytorch.loggers.MLFlowLogger
    init_args:
      experiment_name: enmap_bdforet
      tracking_uri: file:/leonardo/home/userexternal/jleonard/experiments/outputs/mlruns
      run_name: 160126_srf_grouping_run

  callbacks:
    - class_path: RichProgressBar
    - class_path: LearningRateMonitor
      init_args:
        logging_interval: epoch
    - class_path: ModelCheckpoint
      init_args:
        dirpath: /leonardo/home/userexternal/jleonard/experiments/outputs/enmap_bdforet/checkpoints
        filename: '{epoch:02d}'
        monitor: val/loss
        mode: min
        save_last: true
        save_top_k: 1
    - class_path: EarlyStopping
      init_args:
        monitor: val/loss
        mode: min
        patience: 20

  max_epochs: 100
  log_every_n_steps: 5
  default_root_dir: /leonardo/home/userexternal/jleonard/experiments/
data:
  class_path: src.datamodules.enmap_bdforet.EnMAPBDForetDataModule
  init_args:
    batch_size: 16
    num_workers: 2
    patch_size: 224

model:
  class_path: terratorch.tasks.SemanticSegmentationTask
  init_args:
    model_factory: EncoderDecoderFactory
    model_args:
      backbone: terramind_v1_base
      backbone_ckpt_path: /leonardo/home/userexternal/jleonard/experiments/src/ckpt/TerraMind_v1_base.pt
      backbone_img_size: 224
      backbone_in_chans: 12
      backbone_modalities:
        - S2L2A
      backbone_bands:
        S2L2A: ["COASTAL_AEROSOL", "BLUE", "GREEN", "RED", "RED_EDGE_1", "RED_EDGE_2", "RED_EDGE_3", "NIR_BROAD", "NIR_NARROW", "WATER_VAPOR", "SWIR_1", "SWIR_2",]

      necks:
        - name: SelectIndices
          indices: [-1]
        - name: ReshapeTokensToImage
          remove_cls_token: False

      decoder: FCNDecoder
      decoder_channels: 256

      head_dropout: 0.21
      num_classes: 13
      
    loss: ce
    ignore_index: -100
    class_weights: [1.1652, 0.521, 0.9706, 1.1997, 0.5725, 2.221, 1.1205, 1.1452, 0.5706, 0.851, 
                    1.9292, 0.5962, 0.1374] # inverse sqrt of frequencies
    freeze_backbone: false
    freeze_decoder: false
    path_to_record_metrics: /leonardo/home/userexternal/jleonard/experiments/outputs/enmap_bdforet/
    class_names: ["Chesnut", "Deciduous oaks", "Evergreen oaks", "Beech", "Robina", "Douglas-fir", "Hooked/Cembro pine", "Other pine", "Aleppo pine", "Corsican/Black pine", "Scots pine", "Fir/Spruce", "Background"]
optimizer:
  class_path: torch.optim.AdamW #weight decay?
  init_args:
    lr: 3e-5
    weight_decay: 1e-4

lr_scheduler:
  class_path: CosineAnnealingLR
  init_args:
    T_max: 100
    eta_min: 1e-5