# lightning.pytorch==2.1.1
seed_everything: 42
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: 16-mixed
  logger: 
    class_path: lightning.pytorch.loggers.MLFlowLogger
    init_args:
      experiment_name: enmap_bnetd
      tracking_uri: http://localhost:5000
      run_name: '{now:%Y-%m-%d_%H-%M-%S}'
      
  callbacks:
    - class_path: RichProgressBar
    - class_path: LearningRateMonitor
      init_args:
        logging_interval: epoch
    - class_path: ModelCheckpoint
      init_args:
        dirpath: ./outputs/enmap_bnetd/checkpoints
        filename: '{epoch:02d}'
        monitor: val/loss
        mode: min
        save_last: true
        save_top_k: 3
    - class_path: EarlyStopping
      init_args:
        monitor: val/loss
        mode: min
        patience: 20
    
  max_epochs: 100
  log_every_n_steps: 5
  default_root_dir: . 
data:
  class_path: src.datamodules.enmap_bnetd.EnMAPBNETDDataModule
  init_args:
    batch_size: 16
    num_workers: 8
    patch_size: 224

model:
  class_path: terratorch.tasks.SemanticSegmentationTask
  init_args:
    model_factory: EncoderDecoderFactory
    model_args:
      backbone: terramind_v1_base
      backbone_ckpt_path: ./src/ckpt/TerraMind_v1_base.pt
      backbone_img_size: 224
      backbone_in_chans: 12
      backbone_modalities:
        - S2L2A
      backbone_bands:
        S2L2A: ["COASTAL_AEROSOL", "BLUE", "GREEN", "RED", "RED_EDGE_1", "RED_EDGE_2", "RED_EDGE_3", "NIR_BROAD", "NIR_NARROW", "WATER_VAPOR", "SWIR_1", "SWIR_2",]

      necks:
        - name: SelectIndices
          indices: [-1]
        - name: ReshapeTokensToImage
          remove_cls_token: False

      decoder: FCNDecoder
      decoder_channels: 256

      head_dropout: 0.21
      num_classes: 11
    loss: ce
    ignore_index: -100
    freeze_backbone: false
    freeze_decoder: false
    path_to_record_metrics: ./outputs/enmap_bnetd/
    class_names: ["Dense forest", "Light forest", "Forest Gallery", "Forest plantation", "Rubber plantation", "Cashew plantation", "Agricultural area", "Tree savannah", "Human habitat", "Background"]
optimizer:
  class_path: torch.optim.AdamW #weight decay?
  init_args:
    lr: 1e-3 
    weight_decay: 1e-4

lr_scheduler:
  class_path: CosineAnnealingLR
  init_args:
    T_max: 10
    eta_min: 1e-5
